baseurl: ''
exclude: [vendor, deploy_key.enc]

key: htcondor

google_analytics:

markdown_ext : "md"

highlighter: none

collections:
  news:
    output: true
    permalink: /news/:path/
  vulnerabilities:
    output: true
    permalink: /security/vulnerabilities/:path:output_ext
    layout: vulnerabilities
  wiki-pages:
    permalink: /wiki-archive/pages/:path/
    output: true
  software:
    permalink: /:path/
    output: true
  featured-users:
    permalink: /featured-users/:path:output_ext
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "vulnerabilities"
    values:
      layout: vulnerabilities
  -
    scope:
      path: "/news"
    values:
      layout: "news"
  - scope:
      type: "featured-users"
    values:
      layout: "featured-users"

sass:
  style: compressed

plugins:
  - jekyll-redirect-from
  - jekyll-environment-variables
  - jekyll-sitemap

