baseurl: ''
exclude: [vendor, deploy_key.enc]

google_analytics:

markdown_ext : "md"

highlighter: none

collections:
  news:
    output: true
    permalink: /news/:path/
  vulnerabilities:
    output: true
    permalink: /security/vulnerabilities/:path
    layout: vulnerabilities
  wiki-pages:
    permalink: /wiki-archive/pages/:path/
    output: true
  software:
    permalink: /:path/
    output: true
  user-stories:
    permalink: /user-stories/:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "vulnerabilities"
    values:
      layout: vulnerabilities
  -
    scope:
      path: "/news"
    values:
      layout: "news"

sass:
  style: compressed

plugins:
  - jekyll-redirect-from
  - jekyll-environment-variables
  - jekyll-sitemap

