baseurl: ''
exclude: [vendor, deploy_key.enc]

key: htcondor

google_analytics:

markdown_ext : "md"

highlighter: none

collections:
  news:
    output: true
    permalink: /news/:path/
  vulnerabilities:
    output: true
    permalink: /security/vulnerabilities/:path:output_ext
    layout: vulnerabilities
  wiki-pages:
    permalink: /wiki-archive/pages/:path/
    output: true
  software:
    permalink: /:path/
    output: true
  featured-users:
    permalink: /featured-users/:path:output_ext
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: https://htcondor.org/assets/images/Twitter_Image.jpg
  - scope:
      path: ""
      type: "vulnerabilities"
    values:
      layout: vulnerabilities
  - scope:
      path: "/news"
    values:
      layout: "news"
  - scope:
      type: "featured-users"
    values:
      layout: "featured-users"
  - scope:
      type: "wiki-pages"
    values:
      css_extension:
        - href: /assets/css/cvstrac.10.css
        - href: /assets/css/cvstrac.tj.css
        - href: /assets/css/diff2html.css

sass:
  style: compressed

plugins:
  - jekyll-redirect-from
  - jekyll-environment-variables
  - jekyll-sitemap
  - jekyll-seo-tag

description: |
  HTCSS is a specialized workload management system for compute-intensive jobs.
  Built to be flexible, expressive, and compatible with Grid and Cloud computing
  environments HTCSS was made to increase your Computational Throughput.
twitter:
  username: HTCondor
  card: summary_large_image
social:
  name: HTCSS
  links:
    - https://twitter.com/HTCondor
    - https://github.com/htcondor
    - https://www.linkedin.com/school/uwmadison/

webmaster_verifications:
  google: lCkv5T7d4arQ-RPy5tUh6QyB5b3g6dlYtGxotDj1anQ
