baseurl: /htcondor
exclude: [vendor, deploy_key.enc]

markdown_ext : "md"

highlighter: none

collections:
  news:
    output: true
    permalink: /news/:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  style: compact

plugins:
  - jekyll-redirect-from
  - jekyll-environment-variables

