name: Deploy Web Previews
on:
  workflow_dispatch:
  push:
    branches:
      - preview-**
  pull_request:
    branches:
      - preview-**

jobs:
  Build-And-Deploy-Preview:
    runs-on: ubuntu-latest
    env:
      user_email: clock@wisc.edu
      preview_url: https://github.com/htcondor/web-preview.git
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Get branch name
        run: echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Configure for Dev Preview
        run: |
          sed -i "s|baseurl: ''|baseurl: '/web-preview/${{ env.BRANCH_NAME }}'|" _config.yml
          echo "web_preview: true" >> _config.yml
          git config user.name "Automatic preview publish"
          git config user.email ""
          git commit -am "GHA: htcondor/htcondor-web #$GITHUB_RUN_NUMBER"

      - name: Setup SSH Keys and known_hosts
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.WEB_PREVIEW_DEPLOY_KEY }}

      - name: Build and Deploy
        run: |
          git checkout -b temp-branch
          bundle exec jekyll build
          mkdir temp-dir
          mv _site ${{ env.BRANCH_NAME }}
          mv ${{ env.BRANCH_NAME }} temp-dir

          git add temp-dir
          git commit -m "Build Branch Website"
          SPLIT_BRANCH=$(git subtree split --prefix temp-dir temp-branch)

          git remote add web-preview ${{ env.preview_url }}
          git fetch --all
          git checkout -b preview web-preview/main
          git merge $SPLIT_BRANCH -m "Merge Split Branch" --allow-unrelated-histories -X theirs
          git push web-preview HEAD:main
